version: '3.8'

services:
  # Adminer - Web-Interface für die Verwaltung der MySQL-Datenbank
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - webnet

  # MySQL - Datenbank für das Speichern der Projektinformationen
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - webnet

  # Nginx - Webserver für HTTP-Anfragen
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - webnet

  # Node.js - API-Server
  api:
    image: node:latest
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - mysql

networks:
  webnet:
    driver: bridge
